% michael = {char("//Michael's formula calculation");...
% 'vars: isStartOfSession(false);';...
% 'array: ohlcvalues[23](0);';...
% 'IsStartOfSession = _OHLCMulti5(sessBegin,sessEnd,ohlcvalues);'};

Inputs = [Inputs;...
    string(['sessBegin(',num2str(app.SessStart.Value),'),sessEnd(',num2str(app.SessEnd.Value),'),'])];

Vars = [Vars;...
    "isStartOfSession(false),"];
Arrays = [Arrays;
    "ohlcvalues[23](0),"];

Assignments = [Assignments;
    char("//Michael's formula calculation");
    "IsStartOfSession = _OHLCMulti5(sessBegin,sessEnd,ohlcvalues);"];